### PR TITLE
UN-4128 [FIX] Stop the pipeline/ETL list page from 500ing

### PR DESCRIPTION
**Pull request by kirtimanmishrazipstack**
## What

- The Pipeline/ETL list page returns a 500 error instead of the list.

## Why

- A recent change scopes the "workflow" field on a pipeline to only the workflows you actually own, so you can't schedule a colleague's workflow by guessing its ID. It checked "is there an instance at all" to decide when to apply that scoping — but a list request hands it the whole list, not a single pipeline, so that check let a list slip through and crash.

## How

- The check now confirms the instance is actually one `Pipeline`, not just non-empty — `isinstance(self.instance, Pipeline)` in place of `self.instance is not None`. Detail and update requests are unaffected; only the list request was ever passing a non-`Pipeline` value here.

## Can this PR break any existing features? If yes, please list possible items. If no, please explain why. (PS: Admins do not merge the PR without this section filled)

- No — this narrows a check that was too permissive. Every request that used to reach this code and work correctly (create, detail, update) still does; only the list request, which used to crash, now works too.

## Database Migrations

- None.

## Env Config

- None.

## Relevant Docs

- None.

## Related Issues or PRs

- Introduced by #2273 (UN-2868). Found while testing UN-3494 (#2224) locally after merging `main` in — unrelated to that PR's own changes.

## Dependencies Versions

- None.

## Notes on Testing

- Reproduced directly: serializing a pipeline queryset with `many=True` raised `AttributeError: 'list' object has no attribute 'workflow_id'` on `main`; confirmed it no longer does with this fix. Manually verified against a local ETL pipeline list page.

## Checklist

I have read and understood the [Contribution Guidelines](https://docs.unstract.com/unstract/contributing/unstract/).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

https://claude.ai/code/session_018KZLGSa3oWxgVJdFqvRUQX

### CODE REVIEW

File: backend/pipeline_v2/serializers/crud.py [hunk 1]
```diff
@@ -63,7 +63,8 @@ def get_fields(self) -> dict[str, Any]:
         # An update resends the bound workflow unchanged, so keep it
         # selectable: a co-owner of this resource need not own the workflow.
         # ``validate_workflow`` still refuses an actual change.
-        if self.instance is not None:
+        if isinstance(self.instance, Pipeline):
+            # On a list request, ``self.instance`` is the whole queryset, not one row.
```
[the remark this answers is not in the document]
Comment (kirtimanmishrazipstack) [reply backend/pipeline_v2/serializers/crud.py:67]: @greptile-apps Valid concern about directness, though the underlying premise wasn't quite right: the existing `test_list_instance_does_not_crash` already reproduces this exact regression — I reverted the fix locally and confirmed it fails with the same `AttributeError: 'list' object has no attribute 'workflow_id'`. That works because DRF's `many_init` passes the same `instance` arg to the child serializer, so hand-setting `self.instance` to a list is equivalent to going through `many=True`.

Added `test_many_true_construction_does_not_crash`, which calls `PipelineSerializer(queryset, many=True)` directly per your suggestion, to remove any doubt. Verified it also fails against the pre-fix guard with the identical AttributeError, and all 3 tests pass via `tox -e groups -- unit-backend`.

**Review by chandrasekharan-zipstack — APPROVED** [review]
